#!/usr/bin/env python
import sys
import socket
import struct
import os
import signal
import random

def randstr( leng=6 ):
        x = ''
        for i in range(0, leng):
                x += struct.pack('B', random.randint( 0x41, 0x5b ))
        return x

if __name__== '__main__':
  signal.alarm( 5 )
  s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  try:
    s.connect((sys.argv[1], 4321))
  except socket.error, (value,message):
    sys.exit(1)

  os.system('./slafont')
  f = open("slafont.font", 'rb')
  font = f.read()
  f.close()
  data = s.recv(1024)
  while data.startswith('Connect') == False:
    data = s.recv(1024)

  sfd = data[11:data.find(' to view')]
  s.recv(1024)
  port = int(sfd)

  try:
    c = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    c = c.connect( (sys.argv[1], port ) )
  except socket.error, (value,message):
    sys.exit(1)
  signal.alarm( 10 )
  s.send('2\n')
  s.send(struct.pack('I', len(font)))
  s.send(font)
  s.recv(1024)
  s.send('1\n')
  s.send(randstr(5) + '\n')
  s.recv(1024)
  s.send('3\n')
  y = s.recv(1024)
  if y.startswith('Thank you') == False:
    sys.exit(1)
  s.close()
