#!/usr/bin/python

# Availability Check for the Badge Service

import socket               # Import socket module
import sys

if __name__ == "__main__":
	
	# Check arguments
	if ( len (sys.argv) != 2 ):
		print "Need IP address"
		exit(0)

	try:
		team_num = int(sys.argv[1])
	except ValueError, e:
		print "Unknown IP address"
		exit(0)

	print "Team num: %d" % team_num
	
	s = socket.socket()         # Create a socket object
	host = "localhost"
	#host = "10.3.1.16"
	port = 7598                # Reserve a port for your service.

	exit_status = 0
	try:
		s.connect((host, port))
		s.sendall( "TEAM%d" % team_num )
		result = s.recv(1024)

		print "Result: %s\n" % result
		if ( result.find('PASS') != -1 ):
			print "SUCCESS!"
			exit_status = 0
		else:
			print "FAIL!"
			exit_status = -1

	
		s.close                     # Close the socket when done
	except Exception, e:
		print "Socket exception: "
		print e
		pass

	exit( exit_status )
