#!/usr/bin/perl

sub rndStr{ join'', @_[ map{ rand @_ } 1 .. shift ] }

my $SERVICE = 'ombdsu';

if ($#ARGV+1 != 3) {
	print "Usage: deposit-script <team#> <token> <round number>\n";
	exit(-1);
}

$SIG{ALRM} = sub { print "timeout\n"; };
alarm(10);

my $RETVAl = 0;

my $TEAM = $ARGV[0];
my $IP = "10.5.$TEAM.2";
my $TOKEN = $ARGV[1];

`logger -t "$SERVICE-$IP-Deposit" "Attempting token deposit on $IP"`;

`ssh -o ConnectTimeout=2 root\@$IP "echo '$TOKEN' > /home/flags/$SERVICE; chown root /home/flags/$SERVICE; chgrp $SERVICE /home/flags/$SERVICE; chmod 640 /home/flags/$SERVICE"`;
if ($? != 0) {
	$RETVAL = -1;
}

# generate three random files
my $RNDFILE = rndStr 16, 'A'..'Z';
`ssh -o ConnectTimeout=2 root\@$IP "echo '$RNDFILE' > /home/flags/file1; chown root /home/flags/file1; chgrp $SERVICE /home/flags/file1; chmod 640 /home/flags/file1"`;
if ($? != 0) {
	$RETVAL = -1;
}
`echo '$RNDFILE' > $IP-file1`;

my $RNDFILE = rndStr 16, 'A'..'Z';
`ssh -o ConnectTimeout=2 root\@$IP "echo '$RNDFILE' > /home/flags/file2; chown root /home/flags/file2; chgrp $SERVICE /home/flags/file2; chmod 640 /home/flags/file2"`;
if ($? != 0) {
	$RETVAL = -1;
}
`echo '$RNDFILE' > $IP-file2`;

my $RNDFILE = rndStr 16, 'A'..'Z';
`ssh -o ConnectTimeout=2 root\@$IP "echo '$RNDFILE' > /home/flags/file3; chown root /home/flags/file3; chgrp $SERVICE /home/flags/file3; chmod 640 /home/flags/file3"`;
if ($? != 0) {
	$RETVAL = -1;
}
`echo '$RNDFILE' > $IP-file3`;

if ($RETVAL == 0) {
	`logger -t "$SERVICE-$IP-Deposit" "Success"`;
} else {
	`logger -t "$SERVICE-$IP-Deposit" "Fail"`;
}
exit($RETVAL);


