#!/usr/bin/python

import sys
import socket
import struct

from signal import alarm

if __name__ == '__main__':
	ip = 'localhost'
	port = 2000
	team = 'team' + sys.argv[1]

	alarm(30)

	try:
		s = socket.socket( socket.AF_INET, socket.SOCK_STREAM)
		s.connect( (ip, port))
	except:
		print 'FAILED TO CONNECT TO POLLER %s:%d. FIX THIS' %(ip, port)
		sys.exit(-1)

	data = struct.pack('H', len(team)) + team
	s.send(data)

	result = struct.unpack('I', s.recv(4))[0]

	if result == 0:
		print '%s FAILED' %(team)
		sys.exit(-2)
	elif result == 1:
		print '%s SUCCESS' %(team)
		sys.exit(0)
	else:
		print 'POLLER IS BROKEN'
		sys.exit(-3)

	sys.exit(0)
	
